language: node_js
node_js:
  - "stable"
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c "create database authorsHaven_test;" -U postgres
  - npm run migrate
after_success: npm run coverage
