language: node_js
node_js:
  - "stable"
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
  - npm run migrate
after_success: npm run coverage
